name: CI

on: [push, pull_request]

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Use Node.js version 12
      uses: actions/setup-node@v1
      with:
        node-version: '12'

    - name: Yarn install
      run: yarn install

    - name: Run lint
      run: yarn lint

    - name: Generate code coverage
      run: yarn test-with-coverage

    - name: Upload code coverage
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish to NPM
#     if: success() && startsWith(github.ref, 'refs/tags/')
#     For now, try to publish every time
      if: success()
      run: npm publish --access public
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
